
"""modify sku_info index

Revision ID: 4666b186c5ed
Revises: 545c749fcf13
Create Date: 2025-11-10 13:54:57.197908

"""
from alembic import op
import sqlalchemy as sa
# 经常需要 PostgreSQL 方言类型（如 JSONB、UUID 等）
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4666b186c5ed'
down_revision = '545c749fcf13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sku_info_last_changed_at', table_name='sku_info')
    op.drop_index('idx_sku_info_special_end', table_name='sku_info')
    op.create_index('idx_sku_info_last_changed_sku', 'sku_info', ['last_changed_at', 'sku_code'], unique=False)
    op.create_index('idx_sku_info_lower_sku_code', 'sku_info', [sa.text('lower(sku_code)')], unique=False)
    op.create_index('idx_sku_info_special_end_sku', 'sku_info', ['special_price_end_date', 'sku_code'], unique=False)
    op.create_index('idx_sku_info_updated_sku', 'sku_info', ['updated_at', 'sku_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sku_info_updated_sku', table_name='sku_info')
    op.drop_index('idx_sku_info_special_end_sku', table_name='sku_info')
    op.drop_index('idx_sku_info_lower_sku_code', table_name='sku_info')
    op.drop_index('idx_sku_info_last_changed_sku', table_name='sku_info')
    op.create_index('idx_sku_info_special_end', 'sku_info', ['special_price_end_date'], unique=False)
    op.create_index('idx_sku_info_last_changed_at', 'sku_info', ['last_changed_at'], unique=False)
    # ### end Alembic commands ###
