
"""modify cubic weight

Revision ID: 472f62806b14
Revises: 57517cf4becd
Create Date: 2025-11-06 13:03:48.764960

"""
from alembic import op
import sqlalchemy as sa
# 经常需要 PostgreSQL 方言类型（如 JSONB、UUID 等）
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '472f62806b14'
down_revision = '57517cf4becd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_kogan_export_job_sku_unique', 'kogan_export_job_skus', type_='unique')
    op.alter_column('kogan_export_jobs', 'row_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kogan_sku_freight_fee', 'cubic_weight',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kogan_sku_freight_fee', 'cubic_weight',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=True)
    op.alter_column('kogan_export_jobs', 'row_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_unique_constraint('ux_kogan_export_job_sku_unique', 'kogan_export_job_skus', ['job_id', 'sku'])
    # ### end Alembic commands ###
