
"""add cbm to sku_info

Revision ID: 4b892f21ee55
Revises: d528c7d7752a
Create Date: 2025-10-28 16:46:25.441755

"""
from alembic import op
import sqlalchemy as sa
# 经常需要 PostgreSQL 方言类型（如 JSONB、UUID 等）
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4b892f21ee55'
down_revision = 'd528c7d7752a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku_info', sa.Column('cbm', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku_info', 'cbm')
    # ### end Alembic commands ###
