
"""add template index

Revision ID: 545c749fcf13
Revises: 472f62806b14
Create Date: 2025-11-09 22:44:34.889907

"""
from alembic import op
import sqlalchemy as sa
# 经常需要 PostgreSQL 方言类型（如 JSONB、UUID 等）
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '545c749fcf13'
down_revision = '472f62806b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_kogan_export_job_skus_changed_cols_gin', 'kogan_export_job_skus', ['changed_columns'], unique=False, postgresql_using='gin')
    op.create_index('ix_kogan_export_job_skus_job_sku', 'kogan_export_job_skus', ['job_id', 'sku'], unique=False)
    op.create_index('ix_kogan_export_jobs_country_exported', 'kogan_export_jobs', ['country_type', 'exported_at'], unique=False)
    op.create_index('ix_kogan_export_jobs_status_updated', 'kogan_export_jobs', ['status', 'updated_at'], unique=False)
    op.create_index('ix_kogan_template_au_updated', 'kogan_template_au', ['updated_at'], unique=False)
    op.create_index('ux_kogan_template_au_country_sku', 'kogan_template_au', ['country_type', 'sku'], unique=True)
    op.create_index('ix_kogan_template_nz_updated', 'kogan_template_nz', ['updated_at'], unique=False)
    op.create_index('ux_kogan_template_nz_country_sku', 'kogan_template_nz', ['country_type', 'sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_kogan_template_nz_country_sku', table_name='kogan_template_nz')
    op.drop_index('ix_kogan_template_nz_updated', table_name='kogan_template_nz')
    op.drop_index('ux_kogan_template_au_country_sku', table_name='kogan_template_au')
    op.drop_index('ix_kogan_template_au_updated', table_name='kogan_template_au')
    op.drop_index('ix_kogan_export_jobs_status_updated', table_name='kogan_export_jobs')
    op.drop_index('ix_kogan_export_jobs_country_exported', table_name='kogan_export_jobs')
    op.drop_index('ix_kogan_export_job_skus_job_sku', table_name='kogan_export_job_skus')
    op.drop_index('ix_kogan_export_job_skus_changed_cols_gin', table_name='kogan_export_job_skus', postgresql_using='gin')
    # ### end Alembic commands ###
