
"""modify cbm range in sku_info

Revision ID: b168123c0527
Revises: e0f1983c377e
Create Date: 2025-11-20 16:20:57.986440

"""
from alembic import op
import sqlalchemy as sa
# 经常需要 PostgreSQL 方言类型（如 JSONB、UUID 等）
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b168123c0527'
down_revision = 'e0f1983c377e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sku_info', 'cbm',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sku_info', 'cbm',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
