
"""delete variant id index

Revision ID: e0f1983c377e
Revises: 4666b186c5ed
Create Date: 2025-11-10 14:04:53.293022

"""
from alembic import op
import sqlalchemy as sa
# 经常需要 PostgreSQL 方言类型（如 JSONB、UUID 等）
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e0f1983c377e'
down_revision = '4666b186c5ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sku_info_shopify_variant_id', table_name='sku_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sku_info_shopify_variant_id', 'sku_info', ['shopify_variant_id'], unique=False)
    # ### end Alembic commands ###
